static const char wifi_form_html[] =
"<!DOCTYPE html>"
"<html lang='es'>"
"<head>"
"  <meta charset='utf-8'>"
"  <meta name='viewport' content='width=device-width, initial-scale=1'/>"
"  <title>Configurar WiFi</title>"
"  <style>"
"    :root{--bg:#f4f6f8;--card:#fff;--accent:#007acc;--text:#222}"
"    body{margin:0;font-family:Arial,Helvetica,sans-serif;background:var(--bg);color:var(--text);display:flex;align-items:center;justify-content:center;height:100vh;padding:20px}"
"    .card{background:var(--card);border-radius:10px;box-shadow:0 4px 14px rgba(0,0,0,0.08);padding:22px;max-width:900px;width:100%}"
"    h1{margin:0 0 14px;font-size:20px;text-align:center}"
"    form{display:flex;flex-direction:column;gap:10px}"
"    input{padding:12px 10px;font-size:15px;border:1px solid #ddd;border-radius:6px}"
"    button{padding:12px;font-size:16px;border:0;border-radius:6px;background:var(--accent);color:#fff;cursor:pointer}"
"    .hint{font-size:13px;color:#666;text-align:center;margin-top:8px}"
"    /* Desktop layout */"
"    .desktop{display:none}"
"    .desktop .grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:center}"
"    .desktop label{font-size:14px}"
"    /* Mobile layout */"
"    .mobile .big{font-size:18px;padding:14px}"
"    /* Media queries: show mobile for small widths, desktop for larger */"
"    @media (max-width:767px){"
"      .mobile{display:block}"
"      .desktop{display:none}"
"      .card{padding:18px}"
"      h1{font-size:18px}"
"    }"
"    @media (min-width:768px){"
"      .mobile{display:none}"
"      .desktop{display:block}"
"      .card{padding:26px}"
"      h1{font-size:22px}"
"    }"
"  </style>"
"</head>"
"<body>"
"  <div class='card'>"
"    <h1>Configurar WiFi</h1>"
"    <!-- VERSIÓN MÓVIL -->"
"    <div class='mobile'>"
"      <form action='/wifi' method='post' accept-charset='utf-8'>"
"        <input name='ssid' placeholder='SSID (Nombre de la red)' required class='big'/>"
"        <input name='password' type='password' placeholder='Contraseña' class='big'/>"
"        <button type='submit' class='big'>Conectar</button>"
"      </form>"
"      <p class='hint'>Pulsa conectar y espera unos segundos. Si ya hay credenciales guardadas, el dispositivo intentará usarlas.</p>"
"    </div>"
"    <!-- VERSIÓN DESKTOP -->"
"    <div class='desktop'>"
"      <form action='/wifi' method='post' accept-charset='utf-8'>"
"        <div class='grid'>"
"          <div>"
"            <label for='ssid'>SSID</label>"
"            <input id='ssid' name='ssid' placeholder='SSID (Nombre de la red)' required/>"
"          </div>"
"          <div>"
"            <label for='password'>Contraseña</label>"
"            <input id='password' name='password' type='password' placeholder='Contraseña'/>"
"          </div>"
"        </div>"
"        <div style='display:flex;gap:10px;margin-top:12px;justify-content:center'>"
"          <button type='submit'>Conectar</button>"
"        </div>"
"      </form>"
"      <p class='hint'>Versión para escritorio: campos en dos columnas.</p>"
"    </div>"
"  </div>"
"</body>"
"</html>";